# Generated by Django 4.2.23 on 2025-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingsession',
            name='simulation_image',
            field=models.FileField(blank=True, help_text='Generated packing visualization image', null=True, upload_to='simulation_images/'),
        ),
    ]
