# Generated by Django 4.2.23 on 2025-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_packingsession_simulation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingsession',
            name='scene_data',
            field=models.FileField(blank=True, help_text='3D scene data JSON for interactive viewer', null=True, upload_to='scene_data/'),
        ),
        migrations.AlterField(
            model_name='packingsession',
            name='algorithm',
            field=models.CharField(choices=[('corner_height', 'Corner Height Heuristic'), ('random', 'Random Placement')], default='corner_height', help_text='Packing algorithm to use', max_length=20),
        ),
    ]
